
modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/ModMCdl/EndgameExtension/issues" #optional
[[mods]] #mandatory
modId="endgameextension" #mandatory
version="${file.2.0.0}" #mandatory
displayName="Endgame Extension" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/endgame-extension-mod" #optional
logoFile="endgameextension_logo.png" #optional
credits="Thanks for this mod goes to modmcdl and RedRoseWarior1 aka Sammy aka KingOfTheGames" #optional
authors="modmcdl, RedRosewarrior aka Sammy aka KingOfTheGames aka DevMan_Minecraft" #optional
description='''
Expanding and adding to Minecraft's current nether endgame, Endgame Extension adds more function and utilization to the Nether Star, including new "wither-proof" Nether Star Blocks, Wither Tools, and even brings 1.14's Wither Rose into 1.12.2!
'''
[[dependencies.endgameextension]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.endgameextension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
